export const dummyQuestionList = [
  {
    author: 1,
    author_name: "CharmingCheol",
    body: "dsijsdiagoasd",
    bounty: 10,
    created_at: "2021.01.30",
    edited_at: "2021.01.30",
    hashtags: [],
    id: 1,
    is_liked: false,
    like_id: 0,
    title: "title title",
  },
  {
    author: 1,
    author_name: "CharmingCheol",
    body: "dsijsdiagoasd",
    bounty: 10,
    created_at: "2021.01.30",
    edited_at: "2021.01.30",
    hashtags: [],
    id: 2,
    is_liked: false,
    like_id: 0,
    title: "title title",
  },
  {
    author: 1,
    author_name: "CharmingCheol",
    body: "dsijsdiagoasd",
    bounty: 10,
    created_at: "2021.01.30",
    edited_at: "2021.01.30",
    hashtags: [],
    id: 3,
    is_liked: false,
    like_id: 0,
    title: "title title",
  },
  {
    author: 1,
    author_name: "CharmingCheol",
    body: "dsijsdiagoasd",
    bounty: 10,
    created_at: "2021.01.30",
    edited_at: "2021.01.30",
    hashtags: [],
    id: 4,
    is_liked: false,
    like_id: 0,
    title: "title title",
  },
  {
    author: 1,
    author_name: "CharmingCheol",
    body: "dsijsdiagoasd",
    bounty: 10,
    created_at: "2021.01.30",
    edited_at: "2021.01.30",
    hashtags: [],
    id: 5,
    is_liked: false,
    like_id: 0,
    title: "title title",
  },
];

export const dummyProjectList = [
  {
    author_name: "CharmingCheol",
    created_at: "2021.01.30",
    crew_field: "백앤드",
    hashtags: ["백앤드"],
    id: 1,
    is_liked: false,
    like_id: 0,
    title: "esfeafds",
  },
  {
    author_name: "CharmingCheol",
    created_at: "2021.01.30",
    crew_field: "백앤드",
    hashtags: ["백앤드"],
    id: 2,
    is_liked: false,
    like_id: 0,
    title: "esfeafds",
  },
  {
    author_name: "CharmingCheol",
    created_at: "2021.01.30",
    crew_field: "백앤드",
    hashtags: ["백앤드"],
    id: 3,
    is_liked: false,
    like_id: 0,
    title: "esfeafds",
  },
  {
    author_name: "CharmingCheol",
    created_at: "2021.01.30",
    crew_field: "백앤드",
    hashtags: ["백앤드"],
    id: 4,
    is_liked: false,
    like_id: 0,
    title: "esfeafds",
  },
];
